metadata and tooling [ci skip]
- codemeta metadata tweak [ci skip]
- don't update filesize in codemeta - changes by platform and branch

diff --git a/tools/githooks/pre-commit b/tools/githooks/pre-commit
--- a/tools/githooks/pre-commit
+++ b/tools/githooks/pre-commit
@@ -32,7 +32,7 @@ fi
 git diff --cached --name-only |
     grep -q 'DESCRIPTION' &&
     [[ DESCRIPTION -nt codemeta.json ]] && {
-    Rscript -e 'codemetar::write_codemeta()'
+    Rscript -e 'codemetar::write_codemeta(verbose = FALSE, use_filesize = FALSE)'
     git add codemeta.json
     # git commit --amend -m"$(git log --format=%B -n1)" -m"Updated codemeta.json automatically."
     ok=1
@@ -106,5 +106,5 @@ if (( wcres != 0 )); then
     ok=1
 fi
 
-(( ok != 0 )) && echo "githooks/pre-commit failed" >&1 && exit ${ok}
+(( ok != 0 )) && echo "githooks/pre-commit failed" >&1 && exit "${ok}"
 exit 0
