git hook
- no need to rely on ICD_HOME

diff --git a/tools/githooks/pre-commit b/tools/githooks/pre-commit
--- a/tools/githooks/pre-commit
+++ b/tools/githooks/pre-commit
@@ -7,8 +7,8 @@ declare -i wcres=0
 
 MSG="use 'git commit --no-verify' to override this check"
 
-ICD_HOME="$(git rev-parse --show-toplevel)"
-if ! "${ICD_HOME?}/tools/travis-yaml-check.sh"; then
+IH="$(git rev-parse --show-toplevel)"
+if ! "${IH:-.}/tools/travis-yaml-check.sh"; then
     echo ".travis.yml is invalid."
     echo "${MSG}"
     ok=1
@@ -74,7 +74,7 @@ else
 fi
 
 # make sure we usr /usr/bin/env bash for scripts
-find "${ICD_HOME?}" \
+find "${IH?}" \
     -type d -name '.*' -prune -o \
     ! -name "pre-commit" \
     -type f \
@@ -88,10 +88,10 @@ find "${ICD_HOME?}" \
 done
 
 # check bash scripts
-find "${ICD_HOME?}" -type d -name '.*' -prune -o -type f -exec grep -q '#!/usr/bin/env bash' '{}' \; -print |
+find "${IH?}" -type d -name '.*' -prune -o -type f -exec grep -q '#!/usr/bin/env bash' '{}' \; -print |
     while read -r scbash
     do {
-        shellcheck "${scbash}"
+        shellcheck -x "${scbash}"
         ok=1;
     }
 done
@@ -106,5 +106,7 @@ if (( wcres != 0 )); then
     ok=1
 fi
 
-(( ok != 0 )) && echo "githooks/pre-commit failed" >&1 && exit ${ok}
-exit 0
+(( ok != 0 )) &&
+    echo "githooks/pre-commit failed" >&1
+
+exit $((ok))
